#!/usr/bin/env bash

# Run these commands to import the key from 
# PostgreSQL’s official repository to the APT package manager:
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg -

# Refresh APT to synchronize all repositories using this command:
sudo apt update

# Install the latest version of PostgreSQL with APT and sudo privileges:
sudo apt-get -y install postgresql

# To confirm the installation, run this command:
sudo -u postgres psql

# Enter the PostgreSQL version query statement:
SELECT version();
